services:
  silo:
    image: docker.io/pgsty/silo@sha256:635197cb9f36d01bee221d34d1c7d7960f6a95c48b0b6c01d99cd13bdae51a46
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "127.0.0.1:9100:9000"
      - "127.0.0.1:9101:9001"
    volumes:
      - silo-data:/data
    networks:
      - migration-net
    mem_limit: 1g
    cpus: 1.0

volumes:
  silo-data:

networks:
  migration-net:
    external: true
